<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InvoiceBuilder.Database\InvoiceBuilder.Infrastructure.Database.csproj" />
    <ProjectReference Include="..\InvoiceBuilder.Domain\InvoiceBuilder.Domain.csproj" />
  </ItemGroup>

</Project>
