<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\InvoiceBuilder.Application\InvoiceBuilder.Application.csproj" />
    <ProjectReference Include="..\InvoiceBuilder.ServiceDefaults\InvoiceBuilder.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
