<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\InvoiceBuilder.Application\InvoiceBuilder.Application.csproj" />
    <ProjectReference Include="..\InvoiceBuilder.ServiceDefaults\InvoiceBuilder.ServiceDefaults.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Features\Customers\CusromerGetById\" />
    <Folder Include="Features\Customers\CustomerDelete\" />
    <Folder Include="Features\Customers\CustomerUpdate\" />
  </ItemGroup>

</Project>
